var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc(-2,3);
subject.inc(-2,undefined);
subject.inc(0,2);
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','Filename.txt');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.normalize('');
subject.format('421-648-2595','###.###.#### x####',{normalize:true});
subject.format('421-648-2595','###.###.#### x####',{normalize:false});
subject.format('421-648-2595','###.###.#### x####',false);
subject.blackListNumber('212-579-4741');
subject.blackListNumber('836-592-8050');
